<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class As_member_model extends CI_Model
{

    public $table = 'as_member';
    public $id = 'member_id';
	public $email='member_email';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('member_id,member_fullname,member_email,member_username,member_password,member_photo,member_province,member_city,member_chellphone,memner_address,member_status,member_level,member_blokir');
        $this->datatables->from('as_member');
        //add this line for join
        //$this->datatables->join('table2', 'as_member.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('as_member/read/$1'),'Read')." | ".anchor(site_url('as_member/update/$1'),'Update')." | ".anchor(site_url('as_member/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'member_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	function get_by_email($email)
    {
        $this->db->where($this->id, $email);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('member_id', $q);
	$this->db->or_like('member_fullname', $q);
	$this->db->or_like('member_email', $q);
	$this->db->or_like('member_username', $q);
	$this->db->or_like('member_password', $q);
	$this->db->or_like('member_photo', $q);
	$this->db->or_like('member_province', $q);
	$this->db->or_like('member_city', $q);
	$this->db->or_like('member_chellphone', $q);
	$this->db->or_like('memner_address', $q);
	$this->db->or_like('member_status', $q);
	$this->db->or_like('member_level', $q);
	$this->db->or_like('member_blokir', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('member_id', $q);
	$this->db->or_like('member_fullname', $q);
	$this->db->or_like('member_email', $q);
	$this->db->or_like('member_username', $q);
	$this->db->or_like('member_password', $q);
	$this->db->or_like('member_photo', $q);
	$this->db->or_like('member_province', $q);
	$this->db->or_like('member_city', $q);
	$this->db->or_like('member_chellphone', $q);
	$this->db->or_like('memner_address', $q);
	$this->db->or_like('member_status', $q);
	$this->db->or_like('member_level', $q);
	$this->db->or_like('member_blokir', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
	
	    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
	function login($email,$password) {
        $this->db->where('member_email', $email);
        $this->db->where('member_password', $password);
        $query =  $this->db->get('as_member');
        return $query->num_rows();
    }
    
//    untuk mengambil data hasil login
    function data_login($email,$password) {
        $this->db->where('member_email', $email);
        $this->db->where('member_password', $password);
        return $this->db->get('as_member')->row();
    }	

}

/* End of file As_member_model.php */
/* Location: ./application/models/As_member_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-04 07:44:34 */
/* http://harviacode.com */